name: Deploy

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::314407188943:role/github-to-s3
        aws-region: ap-northeast-1
    
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync production/ s3://qpcr-ninja/production/
